# playbook-post-sync.ps1 — Commit, push, and create/update PR after playbook sync.
#
# Checks for changes in the playbook/ directory, commits, pushes to the branch,
# and creates or finds an existing PR.
#
# Usage:  .\scripts\playbook-post-sync.ps1 -RepoUrl <github-repo-url> [-Summary <text>]
# Output: PR URL on the last line of stdout, or "NO_CHANGES" if nothing changed
#
# Exit codes:
#   0 — success (PR URL or NO_CHANGES on last line)
#   1 — push failed
#   2 — PR creation failed
#
# Requires: git, gh (GitHub CLI)

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$RepoUrl,

    [string]$Summary = ''
)

$ErrorActionPreference = 'Stop'
$Branch = 'modernize/playbook-sync'

# Ensure GITHUB_TOKEN is set for gh CLI (needed when running in agent terminals)
if (-not $env:GITHUB_TOKEN -and (Get-Command 'gh' -ErrorAction SilentlyContinue)) {
    try { $env:GITHUB_TOKEN = & gh auth token 2>$null } catch {}
}

# --- Derive temp path (same as pre-sync) ---
$repoName = ($RepoUrl -replace '.*/', '' -replace '\.git$', '').Trim('/')
$TempDir = [System.IO.Path]::GetTempPath()
$RepoDir = Join-Path $TempDir 'modernize-playbook-sync' $repoName

if (-not (Test-Path (Join-Path $RepoDir '.git'))) {
    Write-Host "ERROR: Repository not found at $RepoDir. Run playbook-pre-sync.ps1 first." -ForegroundColor Red
    exit 1
}

Push-Location $RepoDir

# --- Check for changes ---
$hasChanges = $false

# Check tracked file diffs
git diff --quiet -- playbook/ 2>$null
if ($LASTEXITCODE -ne 0) { $hasChanges = $true }

# Check untracked/new files
$statusOutput = git status --porcelain playbook/ 2>$null
if ($statusOutput) { $hasChanges = $true }

if (-not $hasChanges) {
    Write-Host "No changes detected in playbook/ directory." -ForegroundColor Yellow
    Pop-Location
    Write-Output 'NO_CHANGES'
    exit 0
}

# --- Stage and commit ---
Write-Host "Changes detected. Committing..." -ForegroundColor Yellow
git add playbook/
git commit -m "chore: update modernization playbook" 2>&1 | Out-Null

# --- Push ---
Write-Host "Pushing to origin/$Branch..." -ForegroundColor Yellow
git push --set-upstream origin $Branch 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Push failed, attempting pull --rebase and retry..." -ForegroundColor Yellow
    git pull --rebase 2>&1 | Out-Null
    git push --set-upstream origin $Branch 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Failed to push to remote after retry." -ForegroundColor Red
        Pop-Location
        exit 1
    }
}
Write-Host "Pushed successfully." -ForegroundColor Green

# --- Create or find PR ---
try {
    $existingPr = gh pr list --repo $RepoUrl --head $Branch --state open --json url --limit 1 2>$null
}
catch {
    $existingPr = '[]'
}

if ($existingPr -and $existingPr -match '"url"') {
    # Existing PR found
    $prUrl = ($existingPr | ConvertFrom-Json)[0].url
    Write-Host "Found existing PR: $prUrl" -ForegroundColor Yellow

    # Add comment with summary if provided
    if ($Summary) {
        $prBody = @"
## Playbook Update Summary

$Summary

---
Auto-generated by ``modernize playbook sync``.
"@
        gh pr comment $prUrl --body $prBody 2>&1 | Out-Null
    }

    Pop-Location
    Write-Output $prUrl
}
else {
    # No existing PR — create one
    Write-Host "Creating new PR..." -ForegroundColor Yellow

    # Get default branch
    try {
        $defaultBranch = gh repo view $RepoUrl --json defaultBranchRef --jq '.defaultBranchRef.name' 2>$null
    }
    catch {
        $defaultBranch = 'main'
    }
    if (-not $defaultBranch) { $defaultBranch = 'main' }

    # Format PR body
    if ($Summary) {
        $prBody = @"
## Playbook Update Summary

$Summary

---
Auto-generated by ``modernize playbook sync``.
"@
    }
    else {
        $prBody = 'Auto-generated by `modernize playbook sync`.'
    }

    $prResult = gh pr create `
        --repo $RepoUrl `
        --head $Branch `
        --base $defaultBranch `
        --title "chore: update modernization playbook" `
        --body $prBody 2>&1

    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Failed to create pull request. Verify you have permission to create PRs in this repository." -ForegroundColor Red
        Pop-Location
        exit 2
    }

    Write-Host "Created PR: $prResult" -ForegroundColor Green
    Pop-Location
    Write-Output $prResult
}
