#!/usr/bin/env bash
#
# playbook-post-sync.sh — Commit, push, and create/update PR after playbook sync.
#
# Checks for changes in the playbook/ directory, commits, pushes to the branch,
# and creates or finds an existing PR.
#
# Usage:  ./scripts/playbook-post-sync.sh <github-repo-url> [summary-text]
# Output: PR URL on the last line of stdout, or "NO_CHANGES" if nothing changed
#
# Exit codes:
#   0 — success (PR URL or NO_CHANGES on last line)
#   1 — push failed
#   2 — PR creation failed
#
# Requires: git, gh (GitHub CLI)

set -euo pipefail

REPO_URL="${1:?Usage: playbook-post-sync.sh <github-repo-url> [summary-text]}"
SUMMARY="${2:-}"
BRANCH="modernize/playbook-sync"

# Ensure GITHUB_TOKEN is set for gh CLI (needed when running in agent terminals)
if [ -z "${GITHUB_TOKEN:-}" ] && command -v gh &>/dev/null; then
    GITHUB_TOKEN=$(gh auth token 2>/dev/null) && export GITHUB_TOKEN || true
fi

# --- Derive temp path (same as pre-sync) ---
repo_name=$(echo "$REPO_URL" | sed -E 's|.*/([^/]+?)(.git)?/?$|\1|')
TEMP_DIR="${TMPDIR:-${TEMP:-/tmp}}"
REPO_DIR="$TEMP_DIR/modernize-playbook-sync/$repo_name"

if [ ! -d "$REPO_DIR/.git" ]; then
    echo "ERROR: Repository not found at $REPO_DIR. Run playbook-pre-sync.sh first." >&2
    exit 1
fi

cd "$REPO_DIR"

# --- Check for changes ---
has_changes=false

# Check tracked file diffs
if ! git diff --quiet -- playbook/ 2>/dev/null; then
    has_changes=true
fi

# Check untracked/new files
if [ -n "$(git status --porcelain playbook/ 2>/dev/null)" ]; then
    has_changes=true
fi

if [ "$has_changes" = false ]; then
    echo "No changes detected in playbook/ directory." >&2
    echo "NO_CHANGES"
    exit 0
fi

# --- Stage and commit ---
echo "Changes detected. Committing..." >&2
git add playbook/
git commit -m "chore: update modernization playbook" 2>&1 >&2

# --- Push ---
echo "Pushing to origin/$BRANCH..." >&2
if ! git push --set-upstream origin "$BRANCH" 2>&1 >&2; then
    echo "Push failed, attempting pull --rebase and retry..." >&2
    git pull --rebase 2>&1 >&2
    if ! git push --set-upstream origin "$BRANCH" 2>&1 >&2; then
        echo "ERROR: Failed to push to remote after retry." >&2
        exit 1
    fi
fi
echo "Pushed successfully." >&2

# --- Create or find PR ---
existing_pr=$(gh pr list --repo "$REPO_URL" --head "$BRANCH" --state open --json url --limit 1 2>/dev/null || echo "[]")

if echo "$existing_pr" | grep -q '"url"'; then
    # Existing PR found
    pr_url=$(echo "$existing_pr" | sed -n 's/.*"url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
    echo "Found existing PR: $pr_url" >&2

    # Add comment with summary if provided
    if [ -n "$SUMMARY" ]; then
        pr_body=$(cat <<EOF
## Playbook Update Summary

$SUMMARY

---
Auto-generated by \`modernize playbook sync\`.
EOF
)
        gh pr comment "$pr_url" --body "$pr_body" 2>&1 >&2 || true
    fi

    echo "$pr_url"
else
    # No existing PR — create one
    echo "Creating new PR..." >&2

    # Get default branch
    default_branch=$(gh repo view "$REPO_URL" --json defaultBranchRef --jq '.defaultBranchRef.name' 2>/dev/null || echo "main")
    if [ -z "$default_branch" ]; then
        default_branch="main"
    fi

    # Format PR body
    if [ -n "$SUMMARY" ]; then
        pr_body=$(cat <<EOF
## Playbook Update Summary

$SUMMARY

---
Auto-generated by \`modernize playbook sync\`.
EOF
)
    else
        pr_body="Auto-generated by \`modernize playbook sync\`."
    fi

    pr_result=$(gh pr create \
        --repo "$REPO_URL" \
        --head "$BRANCH" \
        --base "$default_branch" \
        --title "chore: update modernization playbook" \
        --body "$pr_body" 2>&1) || {
        echo "ERROR: Failed to create pull request. Verify you have permission to create PRs in this repository." >&2
        exit 2
    }

    echo "Created PR: $pr_result" >&2
    echo "$pr_result"
fi
